spring:
  application:
    name: FindFriend-backend
  datasource:
    url: jdbc:mysql://localhost:3306/partnerma?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fujia
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #redis
  redis:
    port: 6379
    host: localhost
    password: fujia
    database: 2
  mail:
    host: smtp.qq.com
    # QQ邮箱，这里为发件人，填自己的即可
    username: 2153899192@qq.com
    # QQ邮箱授权码
    password: krdjrhytllzmeahh
server:
  port: 8090
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
      timeout: 86400
      store-type: redis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #不加这个就疯狂报错
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)